name: Code sniffer
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
jobs:
  code_sniffer:
    name: Code sniffer
    runs-on: ubuntu-latest
    steps:
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '7.3'
      - name: Checkout code
        uses: actions/checkout@v1
      - name: Download dependencies
        run: composer install --prefer-dist
      - name: Run code sniffer
        run: composer phpcs
