on:
  push:
    tags:
      - '*' # Create for all tags a draft release
name: Publish in Wordpress

jobs:
  tag:
    name: Publish in Wordpress
    runs-on: ubuntu-latest
    steps:
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '7.3'
      - name: Get the version
        id: get_version
        run: echo "VERSION=${GITHUB_REF/refs\/tags\//}" >> $GITHUB_ENV
      - name: Checkout project
        uses: actions/checkout@v2
      - name: Build project
        run: ./bin/release-into-wordpress.sh ${{ env.VERSION }}
      - name: Composer dependencies
        run: composer install --no-dev
      - name: WordPress Plugin Deploy
        uses: nk-o/action-wordpress-plugin-deploy@master
        env:
          SVN_PASSWORD: ${{ secrets.SVN_PASSWORD }}
          SVN_USERNAME: ${{ secrets.SVN_USERNAME }}
          SOURCE_DIR: .release/multisafepay/
          SLUG: multisafepay
